# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameForMatplotLib = QtWidgets.QFrame(self.centralwidget)
        self.frameForMatplotLib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForMatplotLib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameForMatplotLib.setObjectName("frameForMatplotLib")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frameForMatplotLib)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 491, 661))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.testButton1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.testButton1.setObjectName("testButton1")
        self.horizontalLayout_2.addWidget(self.testButton1)
        self.testButton2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.testButton2.setObjectName("testButton2")
        self.horizontalLayout_2.addWidget(self.testButton2)
        self.horizontalLayout.addWidget(self.frameForMatplotLib)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АЭД"))
        self.testButton1.setText(_translate("MainWindow", "PushButton"))
        self.testButton2.setText(_translate("MainWindow", "PushButton"))
