# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameForMatplotLib = QtWidgets.QFrame(self.centralwidget)
        self.frameForMatplotLib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForMatplotLib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameForMatplotLib.setObjectName("frameForMatplotLib")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frameForMatplotLib)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 661))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.testButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.testButton1.setObjectName("testButton1")
        self.gridLayout.addWidget(self.testButton1, 0, 0, 1, 1)
        self.testButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.testButton2.setObjectName("testButton2")
        self.gridLayout.addWidget(self.testButton2, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frameForMatplotLib)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBarFile = QtWidgets.QMenuBar(MainWindow)
        self.menuBarFile.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menuBarFile.setObjectName("menuBarFile")
        self.fileMenu = QtWidgets.QMenu(self.menuBarFile)
        self.fileMenu.setObjectName("fileMenu")
        self.settingMenu = QtWidgets.QMenu(self.menuBarFile)
        self.settingMenu.setObjectName("settingMenu")
        self.helpMenu = QtWidgets.QMenu(self.menuBarFile)
        self.helpMenu.setObjectName("helpMenu")
        MainWindow.setMenuBar(self.menuBarFile)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setObjectName("openFile")
        self.saveFile = QtWidgets.QAction(MainWindow)
        self.saveFile.setObjectName("saveFile")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.fileMenu.addAction(self.openFile)
        self.fileMenu.addAction(self.saveFile)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exit)
        self.menuBarFile.addAction(self.fileMenu.menuAction())
        self.menuBarFile.addAction(self.settingMenu.menuAction())
        self.menuBarFile.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АЭД"))
        self.testButton1.setText(_translate("MainWindow", "testButton1"))
        self.testButton2.setText(_translate("MainWindow", "testButton2"))
        self.fileMenu.setTitle(_translate("MainWindow", "Файл"))
        self.settingMenu.setTitle(_translate("MainWindow", "Настройки"))
        self.helpMenu.setTitle(_translate("MainWindow", "Помощь"))
        self.openFile.setText(_translate("MainWindow", "Открыть файл"))
        self.saveFile.setText(_translate("MainWindow", "Сохранить файл"))
        self.exit.setText(_translate("MainWindow", "Выход"))
